export const animationMap = {
  "drop": "animate_animated  animate__bounceInDown",
  "fade-in": "animate__animated animate__fadeIn",
  "fly-in-bottom": "animate__animated animate__fadeInUpBig",
  "fly-in-top": "animate__animated animate__fadeInDownBig",
  "fly-in-right": "animate__animated animate__fadeInRightBig",
  "fly-in-left": "animate__animated animate__fadeInLeftBig",
  "pulse": "animate__animated animate__pulse",
  "rotate-in-left": " animate__animated animate__rollIn",
  "rotate-in-right": "animate__animated animate__rollOut",
  "twirl-in": "",
  "pan-right": "",
  "pan-up": "",
  "pan-left": "",
  "pan-down": "",
  "zoom-in": "animate__animated animate__zoomIn",
  "zoom-out": "animate__animated animate__zoomOut",
};
