import Head from "next/head";
import { useAmp } from "next/amp";

import supabase, { supbaseDATABASE } from "../lib/supabase";

export const config = {
  amp: true,
};

export default function IndexPage({ data }) {
  const isAmp = useAmp();
  return (
    <>
      <Head>
        <title>Amp generated by webstory.coolhead.in</title>
      </Head>

      <amp-story
        standalone=""
        title="this is an amp story"
        publisher="Coolhead"
        publisher-logo-src="https://coolhead.in/_next/image?url=https%3A%2F%2Fcdn.hashnode.com%2Fres%2Fhashnode%2Fimage%2Fupload%2Fv1621680626975%2FDf9DaCPLu.jpeg%3Fw%3D400%26h%3D400%26fit%3Dcrop%26crop%3Dfaces%26auto%3Dcompress%2Cformat%26format%3Dwebp&w=828&q=75"
        poster-portrait-src="https://images.unsplash.com/photo-1500099817043-86d46000d58f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=Mnw0MDYxOTZ8MHwxfHNlYXJjaHwxfHxzb21ldGhpbmclMjBuZXclMjBhbmQlMjBncmVhdHxlbnwwfDF8fHwxNjc2NjUwNTk5&ixlib=rb-4.0.3&q=80&w=400"
      >
        {data.map((el, i) => {
          return (
            <amp-story-page id={i} key={i}>
              <amp-story-grid-layer template="fill">
                <amp-img
                  src={
                    el.image ||
                    "https://images.unsplash.com/photo-1500099817043-86d46000d58f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=Mnw0MDYxOTZ8MHwxfHNlYXJjaHwxfHxzb21ldGhpbmclMjBuZXclMjBhbmQlMjBncmVhdHxlbnwwfDF8fHwxNjc2NjUwNTk5&ixlib=rb-4.0.3&q=80&w=400"
                  }
                  width="360"
                  height="720"
                  layout="fill"
                  animate-in="fade-in"
                ></amp-img>
              </amp-story-grid-layer>

              <amp-story-grid-layer template="fill">
                <h1
                  animate-in="fade-in"
                  style={{
                    fontSize: el.fontSize,
                    background: el.background,
                    color: el.color,
                    position: "absolute",
                    marginTop: "50%",
                    top: "50%",
                    height: "fit-content",
                  }}
                >
                  {el.text}
                </h1>
              </amp-story-grid-layer>
            </amp-story-page>
          );
        })}
      </amp-story>
    </>
  );
}

export async function getServerSideProps(context) {
  const { data, error } = await supabase.from("story").select("*");

  const jsonData = JSON.parse(data[0].storyData);

  if (data) {
    console.log(data);
  }
  if (error) throw error;

  return {
    props: { data: jsonData }, // will be passed to the page component as props
  };
}
